modLoader="javafml"
loaderVersion="[44,)"
license="MIT"

[[mods]]
modId="bonkbat"
version="${file.jarVersion}"
displayName="Bonk Bat"
description="Bonk your friends."
authors="PlatinPython"

[[dependencies.rgbblocks]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"

[[dependencies.rgbblocks]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.19.4)"
ordering="NONE"
side="BOTH"
