modLoader="javafml"
loaderVersion="[2,)"
license="MIT"
issueTrackerURL="https://github.com/PlatinPython/BonkBat/issues"

[[mods]]
modId="bonkbat"
version="${file.jarVersion}"
displayName="Bonk Bat"
description="This mod enables you to craft a simple wooden bat out of any vanilla wood type. With this, you unleash the power of bonk!"
logoFile="logo.png"
credits="Thanks TobiBenzi for the model."
authors="PlatinPython"
displayURL="https://curseforge.com/minecraft/mc-mods/bonk-bat"

[[mixins]]
config="mixins.bonkbat.json"

[[dependencies.rgbblocks]]
modId="neoforge"
versionRange="[21.0,)"

[[dependencies.rgbblocks]]
modId="minecraft"
versionRange="[1.21,)"
